### ISSUE TITLE
where chiyomeAPIKey

### ISSUE THREAD

**Issue by LegendSenpai** [Eilaluth/ayano#3]
searched everywhere but still couldnt find the chiyomeAPIKey

**Comment by Eilaluth** [comment]
> searched everywhere but still couldnt find the chiyomeAPIKey

Well Chiyome is my personal shortlink ofc you cannot find the API code, but you can contact me at reidho@waifu.club to get the code (for free).

**Comment by LegendSenpai** [comment]
kkk sent
