### ISSUE TITLE
Sadge

### ISSUE THREAD

**Issue by LegendSenpai** [Eilaluth/ayano#4]
i sent you a msg in gmail but i think u didnt see it 😩 do i add u on discord?

**Comment by Eilaluth** [comment]
Wdym? I already send the API Key to your gmail tho

**Comment by Eilaluth** [comment]
Have check your spam?

**Comment by LegendSenpai** [comment]
1 sec

**Comment by LegendSenpai** [comment]
nvm i found it thanks!
